### ISSUE TITLE
Edit friend information from command line

### ISSUE THREAD

**Issue by changecase** [JacobEvelyn/friends#47] opened 2016-01-05 03:23 UTC
Allow users to edit friend information without directly opening `friends.md`.

This might look something like (assuming Jeffrey Lebowski starts off without any nicknames):

```bash
$ friends edit friend "Jeffrey Lebowski" add nickname "The Dude"
Nickname added: Jeffrey Lebowski is also known as "The Dude"

$ friends edit friend "Jeffrey Lebowski" remove nickname "The Dude"
Nickname removed: Jeffrey Lebowski has no nicknames

$ friends edit friend "Jeffrey Lebowski" add nicknames "The Dude", "Jeff"
Nicknames added: Jeffrey Lebowski is also known as "The Dude" and "Jeff"
```

In reference to https://github.com/JacobEvelyn/friends/issues/40#issuecomment-168859530

**Comment by JacobEvelyn** [comment] 2016-01-05 03:26
Yep, I was planning on incorporating this into the nickname work but definitely good to make it explicit. Thanks!

**Comment by changecase** [comment] 2016-01-05 04:57
No problem!

**Comment by JacobEvelyn** [comment] 2016-01-05 05:17
Implementation-wise, I'm treating this as a duplicate of #40.

**Closed by JacobEvelyn** 2016-01-05 05:17 UTC
Labels: duplicate
